language: go
go:
- 1.11.x
- master

os:
- linux
- osx

dist: trusty
sudo: false

env:
  - GO111MODULE=on

install: true

before_install:
  - go get github.com/mattn/goveralls

script:
  - go test -v -mod=vendor ./...
  - $HOME/gopath/bin/goveralls -service=travis-ci
